dnsme:
  image: qtzar/external-dns:latest
  command: -provider=dnsme
  expose:
   - 1000
  environment:
    DNSME_DOMAINID: ${DNSME_DOMAINID}
    DNSME_KEY: ${DNSME_KEY}
    DNSME_SECRET: ${DNSME_SECRET}
    DNSME_SANDBOX: ${DNSME_SANDBOX}
  labels:
    io.rancher.container.create_agent: "true"
    io.rancher.container.agent.role: "external-dns"
